name: Deploy Dev Environment (Swarm)

on:
  push:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Announce Manager
        uses: docker/build-push-action@v4
        with:
          context: ./backend/announce-manager
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/announce-manager:dev

      - name: Build and Push Web Server
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/ecf
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/ecf-front:dev

      - name: Deploy Stack to Swarm
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TARGET_ENV: dev
          IMAGE_TAG: dev
        run: |
          # memo: --with-registry-auth = envoie des identifiants de login
          
          # On remplace les secrets dans le fichier
          sed -i "s/\${{ secrets.DB_PASSWORD }}/$DB_PASSWORD/g" docker-stack-dev.yml
          
          # DÃ©ploiement
          docker stack deploy --with-registry-auth -c docker-stack-dev.yml fimafeng_dev